# Generated by Django 5.2 on 2025-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='images',
            field=models.ImageField(default='test', upload_to='images/'),
            preserve_default=False,
        ),
    ]
