# Generated by Django 5.2 on 2025-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_recipes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='images',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
