# Generated by Django 5.2 on 2025-04-23 21:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_recipes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
