# Generated by Django 5.2 on 2025-04-25 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_recipes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='createdBy',
            field=models.ForeignKey(on_delete=models.SET('[Deleted User]'), to=settings.AUTH_USER_MODEL),
        ),
    ]
